apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  namespace: gmp-system
  name: collector
  labels:
    app.kubernetes.io/name: collector
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: collector
  endpoints:
  - port: prom-metrics
    interval: 10s
  - port: cfg-rel-metrics
    interval: 10s
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  namespace: gmp-system
  name: rule-evaluator
  labels:
    app.kubernetes.io/name: rule-evaluator
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rule-evaluator
  endpoints:
  - port: r-eval-metrics
    interval: 10s
  - port: cfg-rel-metrics
    interval: 10s